// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cache

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockCache
func (_mock *MockCache) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockCache_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockCache_Expecter) Close() *MockCache_Close_Call {
	return &MockCache_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockCache_Close_Call) Run(run func()) *MockCache_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Close_Call) Return(err error) *MockCache_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Close_Call) RunAndReturn(run func() error) *MockCache_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Decr provides a mock function for the type MockCache
func (_mock *MockCache) Decr(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Decr")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Decr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decr'
type MockCache_Decr_Call struct {
	*mock.Call
}

// Decr is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *MockCache_Expecter) Decr(ctx interface{}, key interface{}) *MockCache_Decr_Call {
	return &MockCache_Decr_Call{Call: _e.mock.On("Decr", ctx, key)}
}

func (_c *MockCache_Decr_Call) Run(run func(ctx context.Context, key string)) *MockCache_Decr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCache_Decr_Call) Return(err error) *MockCache_Decr_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Decr_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockCache_Decr_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockCache
func (_mock *MockCache) Get(ctx context.Context, key string, object interface{}) error {
	ret := _mock.Called(ctx, key, object)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = returnFunc(ctx, key, object)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx
//   - key
//   - object
func (_e *MockCache_Expecter) Get(ctx interface{}, key interface{}, object interface{}) *MockCache_Get_Call {
	return &MockCache_Get_Call{Call: _e.mock.On("Get", ctx, key, object)}
}

func (_c *MockCache_Get_Call) Run(run func(ctx context.Context, key string, object interface{})) *MockCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockCache_Get_Call) Return(err error) *MockCache_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Get_Call) RunAndReturn(run func(ctx context.Context, key string, object interface{}) error) *MockCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetBytes provides a mock function for the type MockCache
func (_mock *MockCache) GetBytes(ctx context.Context, key string) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetBytes")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_GetBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBytes'
type MockCache_GetBytes_Call struct {
	*mock.Call
}

// GetBytes is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *MockCache_Expecter) GetBytes(ctx interface{}, key interface{}) *MockCache_GetBytes_Call {
	return &MockCache_GetBytes_Call{Call: _e.mock.On("GetBytes", ctx, key)}
}

func (_c *MockCache_GetBytes_Call) Run(run func(ctx context.Context, key string)) *MockCache_GetBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCache_GetBytes_Call) Return(bytes []byte, err error) *MockCache_GetBytes_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCache_GetBytes_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, error)) *MockCache_GetBytes_Call {
	_c.Call.Return(run)
	return _c
}

// Incr provides a mock function for the type MockCache
func (_mock *MockCache) Incr(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Incr")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Incr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Incr'
type MockCache_Incr_Call struct {
	*mock.Call
}

// Incr is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *MockCache_Expecter) Incr(ctx interface{}, key interface{}) *MockCache_Incr_Call {
	return &MockCache_Incr_Call{Call: _e.mock.On("Incr", ctx, key)}
}

func (_c *MockCache_Incr_Call) Run(run func(ctx context.Context, key string)) *MockCache_Incr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCache_Incr_Call) Return(err error) *MockCache_Incr_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Incr_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockCache_Incr_Call {
	_c.Call.Return(run)
	return _c
}

// Keys provides a mock function for the type MockCache
func (_mock *MockCache) Keys(ctx context.Context, pattern string) ([]string, error) {
	ret := _mock.Called(ctx, pattern)

	if len(ret) == 0 {
		panic("no return value specified for Keys")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, pattern)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, pattern)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_Keys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keys'
type MockCache_Keys_Call struct {
	*mock.Call
}

// Keys is a helper method to define mock.On call
//   - ctx
//   - pattern
func (_e *MockCache_Expecter) Keys(ctx interface{}, pattern interface{}) *MockCache_Keys_Call {
	return &MockCache_Keys_Call{Call: _e.mock.On("Keys", ctx, pattern)}
}

func (_c *MockCache_Keys_Call) Run(run func(ctx context.Context, pattern string)) *MockCache_Keys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCache_Keys_Call) Return(strings []string, err error) *MockCache_Keys_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockCache_Keys_Call) RunAndReturn(run func(ctx context.Context, pattern string) ([]string, error)) *MockCache_Keys_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockCache
func (_mock *MockCache) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockCache_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx
func (_e *MockCache_Expecter) Ping(ctx interface{}) *MockCache_Ping_Call {
	return &MockCache_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockCache_Ping_Call) Run(run func(ctx context.Context)) *MockCache_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCache_Ping_Call) Return(err error) *MockCache_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockCache_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCache
func (_mock *MockCache) Set(ctx context.Context, key string, value []byte) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx
//   - key
//   - value
func (_e *MockCache_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *MockCache_Set_Call {
	return &MockCache_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockCache_Set_Call) Run(run func(ctx context.Context, key string, value []byte)) *MockCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockCache_Set_Call) Return(err error) *MockCache_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value []byte) error) *MockCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetExp provides a mock function for the type MockCache
func (_mock *MockCache) SetExp(ctx context.Context, key string, value []byte, exp time.Duration) error {
	ret := _mock.Called(ctx, key, value, exp)

	if len(ret) == 0 {
		panic("no return value specified for SetExp")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, exp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_SetExp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExp'
type MockCache_SetExp_Call struct {
	*mock.Call
}

// SetExp is a helper method to define mock.On call
//   - ctx
//   - key
//   - value
//   - exp
func (_e *MockCache_Expecter) SetExp(ctx interface{}, key interface{}, value interface{}, exp interface{}) *MockCache_SetExp_Call {
	return &MockCache_SetExp_Call{Call: _e.mock.On("SetExp", ctx, key, value, exp)}
}

func (_c *MockCache_SetExp_Call) Run(run func(ctx context.Context, key string, value []byte, exp time.Duration)) *MockCache_SetExp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockCache_SetExp_Call) Return(err error) *MockCache_SetExp_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_SetExp_Call) RunAndReturn(run func(ctx context.Context, key string, value []byte, exp time.Duration) error) *MockCache_SetExp_Call {
	_c.Call.Return(run)
	return _c
}
